// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAMp8-VzUuVWnuk1i6t-Byjjns7lMn9E',
    appId: '1:313680244954:android:9bd751dd57415e1b7035e3',
    messagingSenderId: '313680244954',
    projectId: 'speak-up-flutter',
    databaseURL: 'https://speak-up-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speak-up-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYMFZCLLKTQvUaj871pSZaj4RyAe3lQM',
    appId: '1:313680244954:ios:9c9c21df340ed3697035e3',
    messagingSenderId: '313680244954',
    projectId: 'speak-up-flutter',
    databaseURL: 'https://speak-up-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speak-up-flutter.appspot.com',
    androidClientId: '313680244954-8d56miqncpq6du3h17ri09nvv2k97fkh.apps.googleusercontent.com',
    iosClientId: '313680244954-a98380hqbfnds42vtajjahal00bt56pr.apps.googleusercontent.com',
    iosBundleId: 'com.tansangle.speakUpFlutter',
  );
}
