import 'package:speak_up/domain/entities/category/category.dart';

const List<Category> categories = [
  Category(id: 0,
      name: 'Active Lifestyle',
      imagePath: '/active_lifestyle.png',
      iconPath: '/active_lifestyle.svg',
      topicIDs: [28, 29, 37, 59]),
  Category(id: 1,
      name: 'Art',
      imagePath: '/art.png',
      iconPath: '/art.svg',
      topicIDs: [14, 42, 61, 73]),
  Category(id: 2,
      name: 'Business',
      imagePath: '/business.png',
      iconPath: '/business.svg',
      topicIDs: [44, 45, 50, 57]),
  Category(id: 3,
      name: 'Community',
      imagePath: '/community.png',
      iconPath: '/community.svg',
      topicIDs: [35, 47]),
  Category(id: 4,
      name: 'Dining',
      imagePath: '/dining.png',
      iconPath: '/dining.svg',
      topicIDs: [2, 24, 31, 52]),
  Category(id: 5,
      name: 'Entertainment',
      imagePath: '/entertainment.png',
      iconPath: '/entertainment.svg',
      topicIDs: [15, 22, 23, 33, 41, 43, 46, 53, 65, 68, 69]),
  Category(id: 6,
      name: 'Fashion',
      imagePath: '/fashion.png',
      iconPath: '/fashion.svg',
      topicIDs: [48, 62, 63, 64]),
  Category(id: 7,
      name: 'Festivities',
      imagePath: '/festivities.png',
      iconPath: '/festivities.svg',
      topicIDs: [30, 34, 36]),
  Category(id: 8,
      name: 'Health',
      imagePath: '/health.png',
      iconPath: '/health.svg',
      topicIDs: [70, 74]),
  Category(id: 9,
      name: 'Literature',
      imagePath: '/literature.png',
      iconPath: '/literature.svg',
      topicIDs: [3, 11, 13]),
  Category(id: 10,
      name: 'Memorable Events',
      imagePath: '/memorable_events.png',
      iconPath: '/memorable_events.svg',
      topicIDs: [6, 9, 12, 17, 51]),
  Category(id: 11,
      name: 'Online Presence',
      imagePath: '/online_presence.png',
      iconPath: '/online_presence.svg',
      topicIDs: [5, 21, 49]),
  Category(id: 12,
      name: 'Personal Development',
      imagePath: '/personal_development.png',
      iconPath: '/personal_development.svg',
      topicIDs: [27, 60, 66, 67, 75]),
  Category(id: 13,
      name: 'Relationships',
      imagePath: '/relationships.png',
      iconPath: '/relationships.svg',
      topicIDs: [1, 7, 8, 18, 19, 26]),
  Category(id: 14,
      name: 'Technology',
      imagePath: '/technology.png',
      iconPath: '/technology.svg',
      topicIDs: [32, 56, 58, 71]),
  Category(id: 15,
      name: 'Travel',
      imagePath: '/travel.png',
      iconPath: '/travel.svg',
      topicIDs: [4, 10, 16, 20, 25, 54, 72]),
  Category(id: 16,
      name: 'Urban Life',
      imagePath: '/urban_life.png',
      iconPath: '/urban_life.svg',
      topicIDs: [38, 39, 40, 55]),
];