import 'package:flutter/material.dart';
import 'package:speak_up/domain/entities/category/category.dart';
import 'package:speak_up/presentation/resources/app_icons.dart';
import 'package:speak_up/presentation/resources/app_images.dart';



List<Widget> images = [
  AppImages.activeLifestyle(),
  AppImages.art(),
  AppImages.business(),
  AppImages.community(),
  AppImages.dining(),
  AppImages.entertainment(),
  AppImages.fashion(),
  AppImages.festivities(),
  AppImages.health(),
  AppImages.literature(),
  AppImages.memorableEvents(),
  AppImages.onlinePresence(),
  AppImages.personalDevelopment(),
  AppImages.relationship(),
  AppImages.technology(),
  AppImages.travel(),
  AppImages.urbanLife(),
];
List<Widget> categoryIcons = [
  AppIcons.activeLifestyle(),
  AppIcons.art(),
  AppIcons.business(),
  AppIcons.community(),
  AppIcons.dining(),
  AppIcons.entertainment(),
  AppIcons.fashion(),
  AppIcons.festivities(),
  AppIcons.health(),
  AppIcons.literature(),
  AppIcons.memorableEvents(),
  AppIcons.onlinePresence(),
  AppIcons.personalDevelopment(),
  AppIcons.relationship(),
  AppIcons.technology(),
  AppIcons.travel(),
  AppIcons.urbanLife(),
];
List<Widget> categoryDarkIcons = [
  AppIcons.activeLifestyle(color: Colors.white),
  AppIcons.art( color: Colors.white),
  AppIcons.business( color: Colors.white),
  AppIcons.community( color: Colors.white),
  AppIcons.dining(  color: Colors.white),
  AppIcons.entertainment( color: Colors.white),
  AppIcons.fashion( color: Colors.white),
  AppIcons.festivities( color: Colors.white),
  AppIcons.health(  color: Colors.white),
  AppIcons.literature(  color: Colors.white),
  AppIcons.memorableEvents( color: Colors.white),
  AppIcons.onlinePresence(  color: Colors.white),
  AppIcons.personalDevelopment(color: Colors.white),
  AppIcons.relationship(  color: Colors.white),
  AppIcons.technology(  color: Colors.white),
  AppIcons.travel(  color: Colors.white),
  AppIcons.urbanLife( color: Colors.white),
];
const List<Category> categories = [
  Category(id: 0,
      name: 'Active Lifestyle',
      topicIDs: [28, 29, 37, 59]),
  Category(id: 1,
      name: 'Art',
      topicIDs: [14, 42, 61, 73]),
  Category(id: 2,
      name: 'Business',
      topicIDs: [44, 45, 50, 57]),
  Category(id: 3,
      name: 'Community',
      topicIDs: [35, 47]),
  Category(id: 4,
      name: 'Dining',
      topicIDs: [2, 24, 31, 52]),
  Category(id: 5,
      name: 'Entertainment',
      topicIDs: [15, 22, 23, 33, 41, 43, 46, 53, 65, 68, 69]),
  Category(id: 6,
      name: 'Fashion',
      topicIDs: [48, 62, 63, 64]),
  Category(id: 7,
      name: 'Festivities',
      topicIDs: [30, 34, 36]),
  Category(id: 8,
      name: 'Health',
      topicIDs: [70, 74]),
  Category(id: 9,
      name: 'Literature',
      topicIDs: [3, 11, 13]),
  Category(id: 10,
      name: 'Memorable Events',
      topicIDs: [6, 9, 12, 17, 51]),
  Category(id: 11,
      name: 'Online Presence',
      topicIDs: [5, 21, 49]),
  Category(id: 12,
      name: 'Personal Development',
      topicIDs: [27, 60, 66, 67, 75]),
  Category(id: 13,
      name: 'Relationships',
      topicIDs: [1, 7, 8, 18, 19, 26]),
  Category(id: 14,
      name: 'Technology',
      topicIDs: [32, 56, 58, 71]),
  Category(id: 15,
      name: 'Travel',
      topicIDs: [4, 10, 16, 20, 25, 54, 72]),
  Category(id: 16,
      name: 'Urban Life',
      topicIDs: [38, 39, 40, 55]),
];