import 'package:flutter/material.dart';
import 'package:speak_up/presentation/resources/app_icons.dart';
import 'package:speak_up/presentation/resources/app_images.dart';

List<Widget> categoryImageList = [
  AppImages.activeLifestyle(),
  AppImages.art(),
  AppImages.business(),
  AppImages.community(),
  AppImages.dining(),
  AppImages.entertainment(),
  AppImages.fashion(),
  AppImages.festivities(),
  AppImages.health(),
  AppImages.literature(),
  AppImages.memorableEvents(),
  AppImages.onlinePresence(),
  AppImages.personalDevelopment(),
  AppImages.relationship(),
  AppImages.technology(),
  AppImages.travel(),
  AppImages.urbanLife(),
];
List<Widget> categoryIcons = [
  AppIcons.activeLifestyle(),
  AppIcons.art(),
  AppIcons.business(),
  AppIcons.community(),
  AppIcons.dining(),
  AppIcons.entertainment(),
  AppIcons.fashion(),
  AppIcons.festivities(),
  AppIcons.health(),
  AppIcons.literature(),
  AppIcons.memorableEvents(),
  AppIcons.onlinePresence(),
  AppIcons.personalDevelopment(),
  AppIcons.relationship(),
  AppIcons.technology(),
  AppIcons.travel(),
  AppIcons.urbanLife(),
];
List<Widget> categoryDarkIcons = [
  AppIcons.activeLifestyle(color: Colors.white),
  AppIcons.art(color: Colors.white),
  AppIcons.business(color: Colors.white),
  AppIcons.community(color: Colors.white),
  AppIcons.dining(color: Colors.white),
  AppIcons.entertainment(color: Colors.white),
  AppIcons.fashion(color: Colors.white),
  AppIcons.festivities(color: Colors.white),
  AppIcons.health(color: Colors.white),
  AppIcons.literature(color: Colors.white),
  AppIcons.memorableEvents(color: Colors.white),
  AppIcons.onlinePresence(color: Colors.white),
  AppIcons.personalDevelopment(color: Colors.white),
  AppIcons.relationship(color: Colors.white),
  AppIcons.technology(color: Colors.white),
  AppIcons.travel(color: Colors.white),
  AppIcons.urbanLife(color: Colors.white),
];
